{{- range $svc, $conf := .Values }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $svc | lower }}
spec:
  selector:
    app: {{ $svc | lower }}
  ports:
    - protocol: TCP
      port: {{ $conf.port }}
      targetPort: {{ $conf.port }}
  type: ClusterIP
{{- end }}