apiGateway:
  image: hamdibg/api-gateway:latest
  replicaCount: 1
  port: 8080

order:
  image: hamdibg/order:latest
  replicaCount: 1
  port: 8081

payment:
  image: hamdibg/payment:latest
  replicaCount: 1
  port: 8082

products:
  image: hamdibg/products:latest
  replicaCount: 1
  port: 8083

users:
  image: hamdibg/users:latest
  replicaCount: 1
  port: 8084

configServer:
  image: hamdibg/config-server:latest
  replicaCount: 1
  port: 8888

eurekaServer:
  image: hamdibg/eureka-server:latest
  replicaCount: 1
  port: 8761