server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: config-server
  zipkin:
    base-url: http://localhost:9411
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
      enabled: false