name: CI/CD Pipeline

on:
  push:
    branches:
      - test

jobs:
  test-build-push-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Run tests & build all microservices
        run: |
          ./mvnw clean package -DskipTests=false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker images
        run: |
          for svc in api-gateway order payment products users config-server eureka-server; do
            docker build -t $DOCKERHUB_USERNAME/$svc:latest $svc
            docker push $DOCKERHUB_USERNAME/$svc:latest
          done

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Deploy via Helm
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}
        run: |
          echo "$KUBECONFIG_DATA" | base64 -d > kubeconfig
          export KUBECONFIG=$(pwd)/kubeconfig
          helm upgrade --install ecommerce helm \
            --set apiGateway.image=$DOCKERHUB_USERNAME/api-gateway:latest \
            --set order.image=$DOCKERHUB_USERNAME/order:latest \
            --set payment.image=$DOCKERHUB_USERNAME/payment:latest \
            --set products.image=$DOCKERHUB_USERNAME/products:latest \
            --set users.image=$DOCKERHUB_USERNAME/users:latest \
            --set configServer.image=$DOCKERHUB_USERNAME/config-server:latest \
            --set eurekaServer.image=$DOCKERHUB_USERNAME/eureka-server:latest
